### ISSUE TITLE
RPM indicator is missing

### ISSUE THREAD

**Issue by luminarious** [ustwo/autocluster#1]
Not sure what percentage of cars you're assuming to be electric or with an automatic transmission, but any car with manual transmission requires RPM indicator to be present. This allows driver to adjust gear ratio and acceleration to increase efficiency and reduce fuel consumption (see also: hypermiling).

In fact, reinforcing gentle behaviour towards the gas pedal increases efficiency and reduces risk in traffic even for electrics and automatics.

**Comment by harshavardhanr** [comment]
Hey @luminarious cheers for the pointer. You are right we took automatic/electric transmission into account in this design and have intentionally left out the rev counter/RPM indicator.
