### ISSUE TITLE
Left/right transition is too distractful

### ISSUE THREAD

**Issue by og2t** [ustwo/autocluster#2]
Sudden side movement of the content would distract me as a driver.

**Comment by harshavardhanr** [comment]
Cheers for the point out!
Yes, we have kept the transitions to a minimum to reduce distraction, and the prototype is just indicative for users to experience the idea. Thus we think there will be little or no movement while actually driving. Only while stopped or on reverse. (Again, actual time based testing will reveal all :) more in our blogpost - http://ustwo.com/blog/cluster/)
