### ISSUE TITLE
Gear indicator order

### ISSUE THREAD

**Issue by kieferm** [ustwo/autocluster#3]
The gear indicator should be reordered to reflect the actual order of the vehicle transmission.  On a vehicle the order is [ P R N D ].  This is an intentional design so that neutral can be accessed in one move from reverse or drive and the engine can be cranked in case of a stall.

An actual vehicle has to move through reverse and neutral to reach drive.  This would cause the indicator to jump around given the order shown in the design images.  If the gear indicator reflects the actual vehicle transmission order then the indicator would move smoothly from one position to the next.

**Comment by lesmo** [comment]
... not to mention that people actually died because of those early P N R D designs.

**Comment by harshavardhanr** [comment]
Cheers for pointing this out guys!
Correcting it right now.
